[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "end-of-file-fixer" }]

[[repos]]
repo = "local"
hooks = [
    { id = "rustfmt", name = "rustfmt", entry = "cargo fmt --all --check", language = "system", pass_filenames = false },
]
